# for format details, see https://docs.github.com/en/actions

name: Validate

on:
  push:
    paths-ignore:
      - ".gitignore"
      - "LICENSE"
      - "README.md"
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  merge_after_validation:
    runs-on: ubuntu-latest
    steps:
      - name: Merge dev with main branch
        uses: dariocurr/validate@main
        with:
          path: .devcontainer/Dockerfile
          from: dev
          to: main
